return {
	["Common"] = {
		name = "Common",
		pullRate = 50,
	},
	["Uncommon"] = {
		name = "Uncommon",
		pullRate = 25,
	},
	["Rare"] = {
		name = "Rare",
		pullRate = 15,
	},
	["Rainbow"] = {
		name = "Rainbow",
		pullRate = 6,
	},
	["Nebula"] = {
		name = "Nebula",
		pullRate = 3,
	},
	["Mythic"] = {
		name = "Mythic",
		pullRate = 0.9,
	},
	["Singularity"] = {
		name = "Singularity",
		pullRate = 0.1,
	},
	["Secret Rare"] = {
		name = "Secret Rare",
		pullRate = 0.001,
		isSecret = true,
	},
}
